### ISSUE TITLE
Does DAFL Support Multiple Target Usage?

### ISSUE THREAD

**Issue by iskindar** [prosyslab/DAFL-artifact#4]
Thank you for open-sourcing this wonderful project. I've encountered an issue when trying to use Sparrow with the DAFL framework.

**Command Used:**
```bash
python3 /benchmark/scripts/run_sparrow.py gif2tga thin
```
**Error Encountered:**
Upon execution, I receive the following fatal error:
```
Fatal error: exception Failure("Error: target not found")
```
**Description of the Issue:**
The error seems to be related to the target provided to Sparrow. When I supply a single line as the target, Sparrow functions correctly without any issues. However, when I attempt to use two lines as targets, as shown below, I encounter the aforementioned error.
```
ngiflib.c:610
ngiflib.c:328
```
**Question:**
Does DAFL support scenarios involving multiple target usages? I'm aware this might be beyond the typical scope of DAFL, but any guidance or workaround would be greatly appreciated.

Thank you for your assistance.

**Comment by goodtaeeun** [comment]
Hi, thank you for your interest in our project.

You are right that currently DAFL does not support multiple targets.
For the workaround, I recommend you to check the discussion section of our [paper](https://prosys.kaist.ac.kr/publications/sec23.pdf). In short, you may run Sparrow separately on each of the targets, and then aggregate the results into a single input file. One possible way of aggregation is taking the union of the instrumentation targets and taking the average of the scores of the def-use graph. However, we do not know the impact of the methods of aggregation since we lack experimental data.

The good news is that we are currently working on extending DAFL to support multiple targets. We will do our best to get you updated as soon as possible.

**Comment by carolemieux** [comment]
Sorry if this was mentioned somewhere else --- does DAFL support multiple targets yet? Thanks!

**Comment by goodtaeeun** [comment]
@carolemieux Unfortunately, not yet. We are still working on it, though!
