### ISSUE TITLE
How to run DAFL locally?

### ISSUE THREAD

**Issue by 5hEn918** [prosyslab/DAFL-artifact#5]
Hi. Currently all the experiments are conducted in the docker environment. Is it ok to run DAFL on the local machine? Is it any installation script for DAFL? Or can u kindly provide the environment dependencies DAFL need?

**Comment by goodtaeeun** [comment]
Hi, it is possible to run DAFL on your local machine.
However, the installation process may vary depending on your system.

All the scripts that are used to set up the Docker environment are provided in the project.
You may refer to those scripts to set up your local environment for DAFL.
I will be happy to help with the troubleshooting.

**Comment by 5hEn918** [comment]
Thanks for your quick response! I will try the provided docker first.

**Comment by null1024-ws** [comment]
I pulled the docker and tried to run the scripts provided in the repo and it worked well. 
And I also copied the docker components into my local machine, as showed in the picture:
![image](https://github.com/prosyslab/DAFL-artifact/assets/79917102/9ebd03f0-5940-448e-8735-6e6cf35129ca)

I have some questions need to be helped:
Can u share the llvm version u used? How to build the sparrow and does it have some dependencies to instsall?
Also I would to know how the smake-out directory to be generated which is the input for static analyzer sparrow.

**Comment by 5hEn918** [comment]
I pulled the docker and tried to run the scripts provided in the repo and it worked well.
And I also copied the docker components into my local machine, as showed in the picture:
![image](https://github.com/prosyslab/DAFL-artifact/assets/161289944/55c498b6-bf67-4392-978b-1f30714bf13d)


I have some questions need to be helped:
Can u share the llvm version u used? How to build the sparrow and does it have some dependencies to instsall?
Also I would to know how the smake-out directory to be generated which is the input for static analyzer sparrow.

Thanks!

**Comment by goodtaeeun** [comment]
Hi,
1. We used llvm version 12 for DAFL, but different versions for other fuzzers due to their dependencies. Refer to our [script](https://github.com/prosyslab/DAFL-artifact/blob/main/docker-setup/checkout_build_install_llvm.sh) that we used to setup our llvm. For llvm used for other fuzzers, refer to their setup scripts and build scripts in https://github.com/prosyslab/DAFL-artifact/tree/main/docker-setup
2. Please refer our [script](https://github.com/prosyslab/DAFL-artifact/blob/main/docker-setup/setup_Sparrow.sh) that we used to set up Sparrow.
3. `smake-out` directory contains the preprocessed files (*.i files) that are emitted during the compilation. We use our tool `smake` to hook up the `make` process and snatch out the preprocessed files. Refer to our [script](https://github.com/prosyslab/DAFL-artifact/blob/main/docker-setup/run-smake.sh) where we generate the contents for the `smake-out` directory.

**Comment by 5hEn918** [comment]
Thanks for your response!
